### ISSUE TITLE
Keep getting not handled exceptions on testnet

### ISSUE THREAD

**Issue by kwunyeung** [virtualeconomy/v-systems#156]
I keep getting these unhandled exceptions on testnet. The node doesn't panic.

```
Oct 21 11:32:29 vsys-validator vsys[26849]: DEBUG v.n.FatalErrorHandler - [5a5f96fc 18.218.106.1:9923] Exception caught
Oct 21 11:32:29 vsys-validator vsys[26849]: java.util.NoSuchElementException: null
Oct 21 11:32:29 vsys-validator vsys[26849]:         at java.util.ArrayDeque.removeFirst(ArrayDeque.java:285)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at java.util.ArrayDeque.remove(ArrayDeque.java:452)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at com.google.common.collect.EvictingQueue.add(EvictingQueue.java:110)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at vsys.network.PeerDatabaseImpl.addCandidate(PeerDatabaseImpl.scala:36)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at vsys.network.PeerSynchronizer.$anonfun$channelRead$7(PeerSynchronizer.scala:47)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at vsys.network.PeerSynchronizer.$anonfun$channelRead$7$adapted(PeerSynchronizer.scala:47)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at scala.collection.Iterator.foreach(Iterator.scala:944)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at scala.collection.Iterator.foreach$(Iterator.scala:944)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at scala.collection.IterableLike.foreach(IterableLike.scala:71)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at vsys.network.PeerSynchronizer.channelRead(PeerSynchronizer.scala:47)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at vsys.network.DiscardingHandler.channelRead(DiscardingHandler.scala:14)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
Oct 21 11:32:29 vsys-validator vsys[26849]:         at java.lang.Thread.run(Thread.java:748)
Oct 21 11:32:30 vsys-validator vsys[26849]: DEBUG v.n.FatalErrorHandler - [c77b9d06 3.130.98.79:9923] Exception caught
Oct 21 11:32:30 vsys-validator vsys[26849]: java.util.NoSuchElementException: null
Oct 21 11:32:30 vsys-validator vsys[26849]:         at java.util.ArrayDeque.removeFirst(ArrayDeque.java:285)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at java.util.ArrayDeque.remove(ArrayDeque.java:452)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at com.google.common.collect.EvictingQueue.add(EvictingQueue.java:110)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at vsys.network.PeerDatabaseImpl.addCandidate(PeerDatabaseImpl.scala:36)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at vsys.network.PeerSynchronizer.$anonfun$channelRead$7(PeerSynchronizer.scala:47)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at vsys.network.PeerSynchronizer.$anonfun$channelRead$7$adapted(PeerSynchronizer.scala:47)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at scala.collection.Iterator.foreach(Iterator.scala:944)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at scala.collection.Iterator.foreach$(Iterator.scala:944)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at scala.collection.IterableLike.foreach(IterableLike.scala:71)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at vsys.network.PeerSynchronizer.channelRead(PeerSynchronizer.scala:47)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at vsys.network.DiscardingHandler.channelRead(DiscardingHandler.scala:14)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
Oct 21 11:32:30 vsys-validator vsys[26849]:         at java.lang.Thread.run(Thread.java:748)
```

**Comment by zl730** [comment]
Which action will cause such exceptions?

**Comment by kwunyeung** [comment]
I haven't done any action there. Just running the node and it has those exceptions.

**Comment by faddat** [comment]
@kwunyeung is this still a problem for you, or may we close the issue?

Thanks!
