### ISSUE TITLE
the problem happened when block synchronizing

### ISSUE THREAD

**Issue by lkk2003rty** [virtualeconomy/v-systems#159]
The progeam exit when synchronize block, the logs as follows.
```
2019-11-17 21:27:44 ERROR [nator-handler-1] v.b.h.HistoryWriterImpl - LevelDB write batch error
org.iq80.leveldb.DBException: Corruption: block checksum mismatch
        at org.fusesource.leveldbjni.internal.JniDB.write(JniDB.java:153)
        at org.fusesource.leveldbjni.internal.JniDB.write(JniDB.java:114)
        at vsys.db.Storage.$anonfun$commit$1(Storage.scala:64)
        at vsys.db.Storage.$anonfun$commit$1$adapted(Storage.scala:62)
        at scala.Option.foreach(Option.scala:257)
        at vsys.db.Storage.commit(Storage.scala:62)
        at vsys.blockchain.history.HistoryWriterImpl.$anonfun$appendBlock$2(HistoryWriterImpl.scala:43)
        at scala.util.Either.map(Either.scala:350)
        at vsys.blockchain.history.HistoryWriterImpl.$anonfun$appendBlock$1(HistoryWriterImpl.scala:33)
        at vsys.utils.Synchronized.synchronizeOperation(Synchronized.scala:82)
        at vsys.utils.Synchronized.synchronizeOperation$(Synchronized.scala:79)
        at vsys.blockchain.history.HistoryWriterImpl.synchronizeOperation(HistoryWriterImpl.scala:16)
        at vsys.utils.Synchronized.write(Synchronized.scala:77)
        at vsys.utils.Synchronized.write$(Synchronized.scala:76)
        at vsys.blockchain.history.HistoryWriterImpl.write(HistoryWriterImpl.scala:16)
        at vsys.blockchain.history.HistoryWriterImpl.appendBlock(HistoryWriterImpl.scala:32)
        at vsys.blockchain.state.BlockchainUpdaterImpl.$anonfun$processBlock$1(BlockchainUpdaterImpl.scala:67)
        at vsys.utils.Synchronized.synchronizeOperation(Synchronized.scala:82)
        at vsys.utils.Synchronized.synchronizeOperation$(Synchronized.scala:79)
        at vsys.blockchain.state.BlockchainUpdaterImpl.synchronizeOperation(BlockchainUpdaterImpl.scala:19)
        at vsys.utils.Synchronized.write(Synchronized.scala:77)
        at vsys.utils.Synchronized.write$(Synchronized.scala:76)
        at vsys.blockchain.state.BlockchainUpdaterImpl.write(BlockchainUpdaterImpl.scala:19)
        at vsys.blockchain.state.BlockchainUpdaterImpl.processBlock(BlockchainUpdaterImpl.scala:61)
        at vsys.blockchain.Coordinator$.$anonfun$appendBlock$4(Coordinator.scala:86)
        at scala.util.Either.flatMap(Either.scala:338)
        at vsys.blockchain.Coordinator$.$anonfun$appendBlock$3(Coordinator.scala:85)
        at scala.util.Either.flatMap(Either.scala:338)
        at vsys.blockchain.Coordinator$.appendBlock(Coordinator.scala:83)
        at vsys.blockchain.Coordinator$.$anonfun$processFork$4(Coordinator.scala:35)
        at scala.collection.Iterator$$anon$10.next(Iterator.scala:457)
        at scala.collection.TraversableOnce.collectFirst(TraversableOnce.scala:145)
        at scala.collection.TraversableOnce.collectFirst$(TraversableOnce.scala:132)
        at scala.collection.SeqViewLike$AbstractTransformed.collectFirst(SeqViewLike.scala:37)
        at vsys.blockchain.Coordinator$.forkApplicationResultEi$1(Coordinator.scala:36)
        at vsys.blockchain.Coordinator$.$anonfun$processFork$13(Coordinator.scala:47)
        at scala.util.Either.flatMap(Either.scala:338)
        at vsys.blockchain.Coordinator$.$anonfun$processFork$12(Coordinator.scala:46)
        at scala.util.Either.flatMap(Either.scala:338)
        at vsys.blockchain.Coordinator$.$anonfun$processFork$9(Coordinator.scala:45)
        at vsys.blockchain.Coordinator$.$anonfun$processFork$9$adapted(Coordinator.scala:44)
        at scala.util.Either.flatMap(Either.scala:338)
        at vsys.blockchain.Coordinator$.processFork(Coordinator.scala:44)
        at vsys.network.CoordinatorHandler.$anonfun$processFork$1(CoordinatorHandler.scala:47)
        at vsys.network.CoordinatorHandler.$anonfun$channelRead$6(CoordinatorHandler.scala:85)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:654)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.fusesource.leveldbjni.internal.NativeDB$DBException: Corruption: block checksum mismatch
        at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200)
        at org.fusesource.leveldbjni.internal.NativeDB.write(NativeDB.java:285)
        at org.fusesource.leveldbjni.internal.JniDB.write(JniDB.java:150)
        ... 54 common frames omitted
```
And I try to restart the program, a new exception founded in the log.
```
2019-11-18 05:28:00 INFO  [main] v.b.s.BlockchainUpdaterImpl - State rebuild started, total blocks: 7604242, persisted: 7597042, topMemDiff: 0, bottomMemDiff: 0
2019-11-18 05:28:00 ERROR [main] v.actor.RootActorSystem$ - Error while initializing actor system vsys
java.lang.Exception: TransactionValidationError(GenericError(Tx id cannot be duplicated. Current height is: 7597043. Tx with such id already present),{"type":5,"id":"Edz6g79UHiscytPY8G1rm3cXbJ7VKytABWSSoH6vdDCw","recipient":"ARKMGddxHQqfji4Te74VyNLAM3rTbiHJ6CC","timestamp":1573997264002496914,"amount":3600000000,"currentBlockHeight":7597043})
        at vsys.blockchain.state.package$EitherExt2.explicitGet(package.scala:20)
        at vsys.blockchain.state.diffs.BlockDiffer$.$anonfun$unsafeDiffMany$1(BlockDiffer.scala:26)
        at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:157)
        at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:157)
        at scala.collection.Iterator.foreach(Iterator.scala:944)
        at scala.collection.Iterator.foreach$(Iterator.scala:944)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:157)
        at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:155)
        at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
        at vsys.blockchain.state.diffs.BlockDiffer$.unsafeDiffMany(BlockDiffer.scala:25)
        at vsys.blockchain.state.BlockchainUpdaterImpl.$anonfun$unsafeDiffByRange$4(BlockchainUpdaterImpl.scala:33)
        at vsys.blockchain.state.StateWriterImpl$.withTime(StateWriter.scala:196)
        at vsys.blockchain.state.StateWriterImpl$.measureLog(StateWriter.scala:208)
        at vsys.blockchain.state.BlockchainUpdaterImpl.unsafeDiffByRange(BlockchainUpdaterImpl.scala:33)
        at vsys.blockchain.state.BlockchainUpdaterImpl.$anonfun$updatePersistedAndInMemory$2(BlockchainUpdaterImpl.scala:52)
        at vsys.blockchain.state.BlockchainUpdaterImpl.$anonfun$updatePersistedAndInMemory$2$adapted(BlockchainUpdaterImpl.scala:51)
        at scala.collection.immutable.Stream.foreach(Stream.scala:530)
        at vsys.blockchain.state.BlockchainUpdaterImpl.$anonfun$updatePersistedAndInMemory$1(BlockchainUpdaterImpl.scala:51)
        at vsys.blockchain.state.BlockchainUpdaterImpl.$anonfun$updatePersistedAndInMemory$1$adapted(BlockchainUpdaterImpl.scala:46)
        at vsys.utils.Synchronized.synchronizeOperation(Synchronized.scala:82)
        at vsys.utils.Synchronized.synchronizeOperation$(Synchronized.scala:79)
        at vsys.blockchain.state.BlockchainUpdaterImpl.synchronizeOperation(BlockchainUpdaterImpl.scala:19)
        at vsys.utils.Synchronized.write(Synchronized.scala:77)
        at vsys.utils.Synchronized.write$(Synchronized.scala:76)
        at vsys.blockchain.state.BlockchainUpdaterImpl.write(BlockchainUpdaterImpl.scala:19)
        at vsys.blockchain.state.BlockchainUpdaterImpl.vsys$blockchain$state$BlockchainUpdaterImpl$$updatePersistedAndInMemory(BlockchainUpdaterImpl.scala:46)
        at vsys.blockchain.state.BlockchainUpdaterImpl$.apply(BlockchainUpdaterImpl.scala:122)
        at vsys.blockchain.history.StorageFactory$.apply(StorageFactory.scala:24)
        at vsys.Application.<init>(Application.scala:50)
        at vsys.Application$$anon$1.<init>(Application.scala:268)
        at vsys.Application$.$anonfun$main$2(Application.scala:268)
        at vsys.Application$.$anonfun$main$2$adapted(Application.scala:258)
        at vsys.actor.RootActorSystem$.start(RootActorSystem.scala:25)
        at vsys.Application$.main(Application.scala:258)
        at vsys.Application.main(Application.scala)
```

**Comment by faddat** [comment]
What version of the software were you using?

What OS were you running on?

If we don't hear back from this user soon, we should close this issue.
