### ISSUE TITLE
start node program fail 

### ISSUE THREAD

**Issue by angelinazf** [virtualeconomy/v-systems#178]
```
2020-03-05 02:58:58 INFO  [main] vsys.Application$ - Starting...
2020-03-05 02:58:59 INFO  [main] kamon.Kamon$Instance - Initializing Kamon...
2020-03-05 02:58:59 INFO  [lt-dispatcher-4] a.event.slf4j.Slf4jLogger - Slf4jLogger started
2020-03-05 02:59:00 INFO  [main] vsys.Application$ - VSYS Core v0.2.1 Blockchain Id: M
2020-03-05 02:59:00 INFO  [main] v.b.s.BlockchainUpdaterImpl - Constructing BlockchainUpdaterImpl, total blocks: 9941231, persisted: 9940731, topMemDiff: 0, bottomMemDiff: 0
2020-03-05 02:59:00 INFO  [main] v.b.s.BlockchainUpdaterImpl - State rebuild started, total blocks: 9941231, persisted: 9940731, topMemDiff: 0, bottomMemDiff: 0
2020-03-05 02:59:02 INFO  [main] v.b.s.BlockchainUpdaterImpl - State rebuild finished, total blocks: 9941231, persisted: 9940731, topMemDiff: 0, bottomMemDiff: 500
2020-03-05 02:59:02 ERROR [main] v.actor.RootActorSystem$ - Error while initializing actor system vsys
java.lang.IllegalArgumentException: Unknown version 155529159 [1.4.196/0]
	at org.h2.mvstore.DataUtils.newIllegalArgumentException(DataUtils.java:728)
	at org.h2.mvstore.DataUtils.checkArgument(DataUtils.java:715)
	at org.h2.mvstore.MVStore.rollbackTo(MVStore.java:2282)
	at org.h2.mvstore.MVStore.verifyLastChunks(MVStore.java:758)
	at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:678)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:358)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2930)
	at vsys.utils.package$.createMVStore(package.scala:59)
	at vsys.network.PeerDatabaseImpl.<init>(PeerDatabaseImpl.scala:19)
	at vsys.Application.run(Application.scala:73)
	at vsys.Application$.$anonfun$main$2(Application.scala:268)
	at vsys.Application$.$anonfun$main$2$adapted(Application.scala:258)
	at vsys.actor.RootActorSystem$.start(RootActorSystem.scala:25)
	at vsys.Application$.main(Application.scala:258)
	at vsys.Application.main(Application.scala)
```

**Comment by ncying** [comment]
it seems that the peer database failed to load. may delete peer.dat and restart the program~

**Comment by angelinazf** [comment]
when i delete peer.dat and restart, it works, but still not sync blocks

```
2020-03-05 03:14:17 ERROR [nator-handler-1] vsys.db.StateMap - LevelDB get error
org.iq80.leveldb.DBException: Corruption: corrupted compressed block contents
 at org.fusesource.leveldbjni.internal.JniDB.get(JniDB.java:90)
 at org.fusesource.leveldbjni.internal.JniDB.get(JniDB.java:77)
 at vsys.db.Storage.get(Storage.scala:20)
 at vsys.db.StateMap.get(StateMap.scala:48)
 at vsys.blockchain.state.reader.StateReaderImpl.$anonfun$isLeaseActive$1(StateReaderImpl.scala:112)
 at vsys.blockchain.state.reader.StateReaderImpl.$anonfun$isLeaseActive$1$adapted(StateReaderImpl.scala:111)
 at vsys.utils.Synchronized.synchronizeOperation(Synchronized.scala:82)
 at vsys.utils.Synchronized.synchronizeOperation$(Synchronized.scala:79)
 at vsys.blockchain.state.reader.StateReaderImpl.synchronizeOperation(StateReaderImpl.scala:13)
 at vsys.utils.Synchronized.read(Synchronized.scala:74)
 at vsys.utils.Synchronized.read$(Synchronized.scala:73)
 at vsys.blockchain.state.reader.StateReaderImpl.read(StateReaderImpl.scala:13)
 at vsys.blockchain.state.reader.StateReaderImpl.isLeaseActive(StateReaderImpl.scala:111)
 at vsys.blockchain.state.reader.CompositeStateReader.$anonfun$isLeaseActive$1(CompositeStateReader.scala:110)
 at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:12)
 at scala.collection.MapLike.getOrElse(MapLike.scala:128)
 at scala.collection.MapLike.getOrElse$(MapLike.scala:126)
 at scala.collection.AbstractMap.getOrElse(Map.scala:59)
 at vsys.blockchain.state.reader.CompositeStateReader.isLeaseActive(CompositeStateReader.scala:110)
 at vsys.blockchain.state.reader.CompositeStateReader$Proxy.isLeaseActive(CompositeStateReader.scala:196)
 at vsys.blockchain.state.reader.CompositeStateReader.$anonfun$isLeaseActive$1(CompositeStateReader.scala:110)
 at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:12)
 at scala.collection.immutable.Map$EmptyMap$.getOrElse(Map.scala:101)
 at vsys.blockchain.state.reader.CompositeStateReader.isLeaseActive(CompositeStateReader.scala:110)
 at vsys.blockchain.state.reader.CompositeStateReader$Proxy.isLeaseActive(CompositeStateReader.scala:196)
 at vsys.blockchain.state.reader.CompositeStateReader.$anonfun$isLeaseActive$1(CompositeStateReader.scala:110)
 at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:12)
 at scala.collection.immutable.Map$EmptyMap$.getOrElse(Map.scala:101)
 at vsys.blockchain.state.reader.CompositeStateReader.isLeaseActive(CompositeStateReader.scala:110)
 at vsys.blockchain.state.diffs.LeaseTransactionsDiff$.$anonfun$leaseCancel$2(LeaseTransactionsDiff.scala:48)
 at scala.util.Either.map(Either.scala:350)
 at vsys.blockchain.state.diffs.LeaseTransactionsDiff$.$anonfun$leaseCancel$1(LeaseTransactionsDiff.scala:47)
 at scala.util.Either.flatMap(Either.scala:338)
 at vsys.blockchain.state.diffs.LeaseTransactionsDiff$.leaseCancel(LeaseTransactionsDiff.scala:46)
 at vsys.blockchain.state.diffs.TransactionDiffer$.$anonfun$apply$7(TransactionDiffer.scala:39)
 at scala.util.Either.flatMap(Either.scala:338)
 at vsys.blockchain.state.diffs.TransactionDiffer$.$anonfun$apply$6(TransactionDiffer.scala:30)
 at scala.util.Either.flatMap(Either.scala:338)
 at vsys.blockchain.state.diffs.TransactionDiffer$.$anonfun$apply$5(TransactionDiffer.scala:29)
 at scala.util.Either.flatMap(Either.scala:338)
 at vsys.blockchain.state.diffs.TransactionDiffer$.$anonfun$apply$4(TransactionDiffer.scala:28)
 at scala.util.Either.flatMap(Either.scala:338)
 at vsys.blockchain.state.diffs.TransactionDiffer$.$anonfun$apply$3(TransactionDiffer.scala:27)
 at scala.util.Either.flatMap(Either.scala:338)
 at vsys.blockchain.state.diffs.TransactionDiffer$.$anonfun$apply$2(TransactionDiffer.scala:26)
 at scala.util.Either.flatMap(Either.scala:338)
 at vsys.blockchain.state.diffs.TransactionDiffer$.$anonfun$apply$1(TransactionDiffer.scala:25)
 at scala.util.Either.flatMap(Either.scala:338)
 at vsys.blockchain.state.diffs.TransactionDiffer$.apply(TransactionDiffer.scala:24)
 at vsys.blockchain.state.diffs.BlockDiffer$.$anonfun$apply$1(BlockDiffer.scala:38)
 at vsys.blockchain.state.diffs.BlockDiffer$.$anonfun$apply$3(BlockDiffer.scala:43)
 at scala.util.Either.flatMap(Either.scala:338)
 at vsys.blockchain.state.diffs.BlockDiffer$.$anonfun$apply$2(BlockDiffer.scala:42)
 at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:122)
 at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:118)
 at scala.collection.immutable.List.foldLeft(List.scala:86)
 at vsys.blockchain.state.diffs.BlockDiffer$.apply(BlockDiffer.scala:42)
 at vsys.blockchain.state.diffs.BlockDiffer$.$anonfun$fromBlock$1(BlockDiffer.scala:22)
 at scala.util.Either.flatMap(Either.scala:338)
 at vsys.blockchain.state.diffs.BlockDiffer$.fromBlock(BlockDiffer.scala:22)
 at vsys.blockchain.state.BlockchainUpdaterImpl.$anonfun$processBlock$4(BlockchainUpdaterImpl.scala:67)
 at vsys.blockchain.history.HistoryWriterImpl.$anonfun$appendBlock$1(HistoryWriterImpl.scala:33)
 at vsys.utils.Synchronized.synchronizeOperation(Synchronized.scala:82)
 at vsys.utils.Synchronized.synchronizeOperation$(Synchronized.scala:79)
 at vsys.blockchain.history.HistoryWriterImpl.synchronizeOperation(HistoryWriterImpl.scala:16)
 at vsys.utils.Synchronized.write(Synchronized.scala:77)
 at vsys.utils.Synchronized.write$(Synchronized.scala:76)
 at vsys.blockchain.history.HistoryWriterImpl.write(HistoryWriterImpl.scala:16)
 at vsys.blockchain.history.HistoryWriterImpl.appendBlock(HistoryWriterImpl.scala:32)
 at vsys.blockchain.state.BlockchainUpdaterImpl.$anonfun$processBlock$1(BlockchainUpdaterImpl.scala:67)
 at vsys.utils.Synchronized.synchronizeOperation(Synchronized.scala:82)
 at vsys.utils.Synchronized.synchronizeOperation$(Synchronized.scala:79)
 at vsys.blockchain.state.BlockchainUpdaterImpl.synchronizeOperation(BlockchainUpdaterImpl.scala:19)
 at vsys.utils.Synchronized.write(Synchronized.scala:77)
 at vsys.utils.Synchronized.write$(Synchronized.scala:76)
 at vsys.blockchain.state.BlockchainUpdaterImpl.write(BlockchainUpdaterImpl.scala:19)
 at vsys.blockchain.state.BlockchainUpdaterImpl.processBlock(BlockchainUpdaterImpl.scala:61)
 at vsys.blockchain.Coordinator$.$anonfun$appendBlock$4(Coordinator.scala:86)
 at scala.util.Either.flatMap(Either.scala:338)
 at vsys.blockchain.Coordinator$.$anonfun$appendBlock$3(Coordinator.scala:85)
 at scala.util.Either.flatMap(Either.scala:338)
 at vsys.blockchain.Coordinator$.appendBlock(Coordinator.scala:83)
 at vsys.blockchain.Coordinator$.$anonfun$processFork$4(Coordinator.scala:35)
 at scala.collection.Iterator$$anon$10.next(Iterator.scala:457)
 at scala.collection.TraversableOnce.collectFirst(TraversableOnce.scala:145)
 at scala.collection.TraversableOnce.collectFirst$(TraversableOnce.scala:132)
 at scala.collection.SeqViewLike$AbstractTransformed.collectFirst(SeqViewLike.scala:37)
 at vsys.blockchain.Coordinator$.forkApplicationResultEi$1(Coordinator.scala:36)
 at vsys.blockchain.Coordinator$.$anonfun$processFork$13(Coordinator.scala:47)
 at scala.util.Either.flatMap(Either.scala:338)
 at vsys.blockchain.Coordinator$.$anonfun$processFork$12(Coordinator.scala:46)
 at scala.util.Either.flatMap(Either.scala:338)
 at vsys.blockchain.Coordinator$.$anonfun$processFork$9(Coordinator.scala:45)
 at vsys.blockchain.Coordinator$.$anonfun$processFork$9$adapted(Coordinator.scala:44)
 at scala.util.Either.flatMap(Either.scala:338)
 at vsys.blockchain.Coordinator$.processFork(Coordinator.scala:44)
 at vsys.network.CoordinatorHandler.$anonfun$processFork$1(CoordinatorHandler.scala:47)
 at vsys.network.CoordinatorHandler.$anonfun$channelRead$6(CoordinatorHandler.scala:85)
 at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:654)
 at scala.util.Success.$anonfun$map$1(Try.scala:251)
 at scala.util.Success.map(Try.scala:209)
 at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
 at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
 at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
 at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)
Caused by: org.fusesource.leveldbjni.internal.NativeDB$DBException: Corruption: corrupted compressed block contents
 at org.fusesource.leveldbjni.internal.NativeDB.get(NativeDB.java:316)
 at org.fusesource.leveldbjni.internal.NativeDB.get(NativeDB.java:300)
 at org.fusesource.leveldbjni.internal.NativeDB.get(NativeDB.java:293)
 at org.fusesource.leveldbjni.internal.JniDB.get(JniDB.java:85)
 ... 107 common frames omitted
2020-03-05 03:14:17 WARN  [nator-handler-1] v.blockchain.Coordinator$ - Can't process fork starting with 28gLMtpcyNoaxkJLCCZvFochmuNRtWVT3CDDgnsKY7Jj2TeDHWWy1j93BHJZWrw7iQZNTc5iUkWDwnaiVuP2HcKy, error appending block 5gnaRTWM3JJhrQf58wnu2CZfcRcJnZS7MwXuYbXYC2ppyYr6r5dhYs93zhMEieUcVUUwrLR98teAJrXJWwRSviR1: TransactionValidationError(GenericError(Cannot cancel already cancelled lease),{"type":4,"id":"3DiWeyxXgpRDgVttpxiSb278PF9dsgmDsVuKMCMrSmNm","fee":10000000,"timestamp":1583375904290000000,"proofs":[{"proofType":"Curve25519","publicKey":"2vQbUegodVC8gCJY4Q8CQsBuop1k4uHGDMTEVaNUmaC8","address":"ARNnkQFdhQXRsFx3HAuA7XRQkLPGhYGsm5A","signature":"5RWYG1rseb65MGAE2DimNX3mSivigvWWeMZZGan67UJZWP3JNmHkeDgauiRfxNxzZ8BXfpx1BQA392s8h5WdgLBf"}],"feeScale":100,"leaseId":"7suwp5iLxWRA2EHVZ912XcnJQx2MrQAcB7VbFaEDRqTY"})
2020-03-05 03:14:17 WARN  [nator-handler-1] v.n.CoordinatorHandler - Error appending extension [5gnaRTWM3JJhrQf58wnu2CZfcRcJnZS7MwXuYbXYC2ppyYr6r5dhYs93zhMEieUcVUUwrLR98teAJrXJWwRSviR1..5kTxxA3U1Q6NeVmGWeLhoLfPvwhExEjxFxCMn4vm5yKsAAeXyZz8TRBVsCy9JYhVzHnVX9ZRdFY2By3MyWQDVq7o]: TransactionValidationError(GenericError(Cannot cancel already cancelled lease),{"type":4,"id":"3DiWeyxXgpRDgVttpxiSb278PF9dsgmDsVuKMCMrSmNm","fee":10000000,"timestamp":1583375904290000000,"proofs":[{"proofType":"Curve25519","publicKey":"2vQbUegodVC8gCJY4Q8CQsBuop1k4uHGDMTEVaNUmaC8","address":"ARNnkQFdhQXRsFx3HAuA7XRQkLPGhYGsm5A","signature":"5RWYG1rseb65MGAE2DimNX3mSivigvWWeMZZGan67UJZWP3JNmHkeDgauiRfxNxzZ8BXfpx1BQA392s8h5WdgLBf"}],"feeScale":100,"leaseId":"7suwp5iLxWRA2EHVZ912XcnJQx2MrQAcB7VbFaEDRqTY"})
```

**Comment by ncying** [comment]
Since the last block of the local database(in memory diff), it can be solved by rollback one or two blocks in this case. Since the memory diff is custom so it only suggests to rollback a small size of blocks. Or it should re-sync the whole database.

Some suggestions about the cases:
1. For backup node, may stop the service weekly and backup the db, i think a weekly backup may enough in the current stage. the node can start fastly by using the correct backup data.

2. Before the rollback operation, backup your current db first.

**Comment by ncying** [comment]
In addition, we suggest running a backup node for solving such an incident case. One can switch to the backup node fastly.

Manually rollback the block may be a solution for some cases, but it is not the common strategy for solving the problems.

Compare the two solutions: One is rollback one block manually, another one is starting from the correct backup database and re-sync 10000+ blocks. My suggestion is always the second one.

**Comment by faddat** [comment]
If we don't hear back from this user soon, we should probably close this issue.
