### ISSUE TITLE
unit test unexpected failure

### ISSUE THREAD

**Issue by zl730** [virtualeconomy/v-systems#40]
Sometimes this error occurs in unit test: 
```scala
[info]   DecoderException was thrown during property evaluation.
[info]   Message: java.lang.IllegalArgumentException: minimumReadableBytes: -100 (expected: >= 0)
[info]   Occurred when passed generated values (...)
````

**Comment by zl730** [comment]
```
 - should blacklist a node sends an invalid handshake *** FAILED *** (65 milliseconds)
[info]   DecoderException was thrown during property evaluation.
[info]     Message: java.lang.IllegalArgumentException: minimumReadableBytes: -93 (expected: >= 0)
[info]     Occurred when passed generated values (
[info]       arg0 = Array(2, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 120, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 3, -127, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 121, 0, 0, 0, 0, 0, 0, 0, 1, -128, 0, 0, 0, 0, 92, -93, 56, 76)
[info]     )
[info]   org.scalatest.exceptions.GeneratorDrivenPropertyCheckFailedException:
[info]   at org.scalatest.enablers.CheckerAsserting$$anon$2.indicateFailure(CheckerAsserting.scala:232)
[info]   at org.scalatest.enablers.CheckerAsserting$$anon$2.indicateFailure(CheckerAsserting.scala:220)
[info]   at org.scalatest.enablers.UnitCheckerAsserting$CheckerAssertingImpl.check(CheckerAsserting.scala:159)
[info]   at org.scalatest.prop.GeneratorDrivenPropertyChecks.forAll(GeneratorDrivenPropertyChecks.scala:944)
[info]   at org.scalatest.prop.GeneratorDrivenPropertyChecks.forAll$(GeneratorDrivenPropertyChecks.scala:920)
[info]   at com.wavesplatform.network.HandshakeDecoderSpec.forAll(HandshakeDecoderSpec.scala:16)
[info]   at com.wavesplatform.network.HandshakeDecoderSpec.$anonfun$new$2(HandshakeDecoderSpec.scala:88)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.FreeSpecLike$$anon$1.apply(FreeSpecLike.scala:407)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[info]   at com.wavesplatform.network.HandshakeDecoderSpec.org$scalamock$scalatest$AbstractMockFactory$$super$withFixture(HandshakeDecoderSpec.scala:16)
[info]   at org.scalamock.scalatest.AbstractMockFactory.$anonfun$withFixture$1(AbstractMockFactory.scala:35)
[info]   at org.scalamock.MockFactoryBase.withExpectations(MockFactoryBase.scala:55)
[info]   at org.scalamock.MockFactoryBase.withExpectations$(MockFactoryBase.scala:47)
[info]   at com.wavesplatform.network.HandshakeDecoderSpec.withExpectations(HandshakeDecoderSpec.scala:16)
[info]   at org.scalamock.scalatest.AbstractMockFactory.withFixture(AbstractMockFactory.scala:34)
[info]   at org.scalamock.scalatest.AbstractMockFactory.withFixture$(AbstractMockFactory.scala:31)
[info]   at com.wavesplatform.network.HandshakeDecoderSpec.withFixture(HandshakeDecoderSpec.scala:16)
[info]   at org.scalatest.FreeSpecLike.invokeWithFixture$1(FreeSpecLike.scala:405)
[info]   at org.scalatest.FreeSpecLike.$anonfun$runTest$1(FreeSpecLike.scala:417)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.FreeSpecLike.runTest(FreeSpecLike.scala:417)
[info]   at org.scalatest.FreeSpecLike.runTest$(FreeSpecLike.scala:399)
[info]   at org.scalatest.FreeSpec.runTest(FreeSpec.scala:1739)
[info]   at org.scalatest.FreeSpecLike.$anonfun$runTests$1(FreeSpecLike.scala:476)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
[info]   at scala.collection.immutable.List.foreach(List.scala:389)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[info]   at org.scalatest.FreeSpecLike.runTests(FreeSpecLike.scala:476)
[info]   at org.scalatest.FreeSpecLike.runTests$(FreeSpecLike.scala:475)
[info]   at org.scalatest.FreeSpec.runTests(FreeSpec.scala:1739)
[info]   at org.scalatest.Suite.run(Suite.scala:1147)
[info]   at org.scalatest.Suite.run$(Suite.scala:1129)
[info]   at org.scalatest.FreeSpec.org$scalatest$FreeSpecLike$$super$run(FreeSpec.scala:1739)
[info]   at org.scalatest.FreeSpecLike.$anonfun$run$1(FreeSpecLike.scala:520)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[info]   at org.scalatest.FreeSpecLike.run(FreeSpecLike.scala:520)
[info]   at org.scalatest.FreeSpecLike.run$(FreeSpecLike.scala:519)
[info]   at org.scalatest.FreeSpec.run(FreeSpec.scala:1739)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:507)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:106)
[info]   at sbt.TestRunner.run(TestFramework.scala:117)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:262)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:233)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:262)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:262)
[info]   at sbt.TestFunction.apply(TestFramework.scala:271)
[info]   at sbt.Tests$.processRunnable$1(Tests.scala:307)
[info]   at sbt.Tests$.$anonfun$makeSerial$1(Tests.scala:313)
[info]   at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
[info]   at sbt.std.Transform$$anon$4.work(System.scala:66)
[info]   at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[info]   at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[info]   at sbt.Execute.work(Execute.scala:271)
[info]   at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[info]   at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:748)
[info]   Cause: io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: minimumReadableBytes: -93 (expected: >= 0)
[info]   at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:421)
[info]   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[info]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[info]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[info]   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[info]   at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[info]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[info]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[info]   at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[info]   at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:325)
[info]   at com.wavesplatform.network.HandshakeDecoderSpec.$anonfun$new$3(HandshakeDecoderSpec.scala:95)
[info]   at org.scalatest.prop.GeneratorDrivenPropertyChecks.liftedTree9$1(GeneratorDrivenPropertyChecks.scala:931)
[info]   at org.scalatest.prop.GeneratorDrivenPropertyChecks.$anonfun$forAll$7(GeneratorDrivenPropertyChecks.scala:930)
[info]   at org.scalacheck.Prop$.$anonfun$forAllShrink$2(Prop.scala:712)
[info]   at org.scalacheck.Prop$.secure(Prop.scala:456)
[info]   at org.scalacheck.Prop$.result$1(Prop.scala:712)
[info]   at org.scalacheck.Prop$.$anonfun$forAllShrink$1(Prop.scala:749)
[info]   at org.scalacheck.Prop$.$anonfun$apply$1(Prop.scala:292)
[info]   at org.scalacheck.PropFromFun.apply(Prop.scala:22)
[info]   at org.scalacheck.Test$.workerFun$1(Test.scala:294)
[info]   at org.scalacheck.Test$.$anonfun$check$1(Test.scala:323)
[info]   at org.scalacheck.Test$.$anonfun$check$1$adapted(Test.scala:323)
[info]   at org.scalacheck.Platform$.runWorkers(Platform.scala:40)
[info]   at org.scalacheck.Test$.check(Test.scala:323)
[info]   at org.scalatest.enablers.UnitCheckerAsserting$CheckerAssertingImpl.check(CheckerAsserting.scala:89)
[info]   at org.scalatest.prop.GeneratorDrivenPropertyChecks.forAll(GeneratorDrivenPropertyChecks.scala:944)
[info]   at org.scalatest.prop.GeneratorDrivenPropertyChecks.forAll$(GeneratorDrivenPropertyChecks.scala:920)
[info]   at com.wavesplatform.network.HandshakeDecoderSpec.forAll(HandshakeDecoderSpec.scala:16)
[info]   at com.wavesplatform.network.HandshakeDecoderSpec.$anonfun$new$2(HandshakeDecoderSpec.scala:88)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.FreeSpecLike$$anon$1.apply(FreeSpecLike.scala:407)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[info]   at com.wavesplatform.network.HandshakeDecoderSpec.org$scalamock$scalatest$AbstractMockFactory$$super$withFixture(HandshakeDecoderSpec.scala:16)
[info]   at org.scalamock.scalatest.AbstractMockFactory.$anonfun$withFixture$1(AbstractMockFactory.scala:35)
[info]   at org.scalamock.MockFactoryBase.withExpectations(MockFactoryBase.scala:55)
[info]   at org.scalamock.MockFactoryBase.withExpectations$(MockFactoryBase.scala:47)
[info]   at com.wavesplatform.network.HandshakeDecoderSpec.withExpectations(HandshakeDecoderSpec.scala:16)
[info]   at org.scalamock.scalatest.AbstractMockFactory.withFixture(AbstractMockFactory.scala:34)
[info]   at org.scalamock.scalatest.AbstractMockFactory.withFixture$(AbstractMockFactory.scala:31)
[info]   at com.wavesplatform.network.HandshakeDecoderSpec.withFixture(HandshakeDecoderSpec.scala:16)
[info]   at org.scalatest.FreeSpecLike.invokeWithFixture$1(FreeSpecLike.scala:405)
[info]   at org.scalatest.FreeSpecLike.$anonfun$runTest$1(FreeSpecLike.scala:417)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.FreeSpecLike.runTest(FreeSpecLike.scala:417)
[info]   at org.scalatest.FreeSpecLike.runTest$(FreeSpecLike.scala:399)
[info]   at org.scalatest.FreeSpec.runTest(FreeSpec.scala:1739)
[info]   at org.scalatest.FreeSpecLike.$anonfun$runTests$1(FreeSpecLike.scala:476)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
[info]   at scala.collection.immutable.List.foreach(List.scala:389)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[info]   at org.scalatest.FreeSpecLike.runTests(FreeSpecLike.scala:476)
[info]   at org.scalatest.FreeSpecLike.runTests$(FreeSpecLike.scala:475)
[info]   at org.scalatest.FreeSpec.runTests(FreeSpec.scala:1739)
[info]   at org.scalatest.Suite.run(Suite.scala:1147)
[info]   at org.scalatest.Suite.run$(Suite.scala:1129)
[info]   at org.scalatest.FreeSpec.org$scalatest$FreeSpecLike$$super$run(FreeSpec.scala:1739)
[info]   at org.scalatest.FreeSpecLike.$anonfun$run$1(FreeSpecLike.scala:520)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[info]   at org.scalatest.FreeSpecLike.run(FreeSpecLike.scala:520)
[info]   at org.scalatest.FreeSpecLike.run$(FreeSpecLike.scala:519)
[info]   at org.scalatest.FreeSpec.run(FreeSpec.scala:1739)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:507)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:106)
[info]   at sbt.TestRunner.run(TestFramework.scala:117)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:262)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:233)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:262)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:262)
[info]   at sbt.TestFunction.apply(TestFramework.scala:271)
[info]   at sbt.Tests$.processRunnable$1(Tests.scala:307)
[info]   at sbt.Tests$.$anonfun$makeSerial$1(Tests.scala:313)
[info]   at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
[info]   at sbt.std.Transform$$anon$4.work(System.scala:66)
[info]   at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[info]   at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[info]   at sbt.Execute.work(Execute.scala:271)
[info]   at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[info]   at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:748)
[info]   Cause: java.lang.IllegalArgumentException: minimumReadableBytes: -93 (expected: >= 0)
[info]   at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1390)
[info]   at io.netty.buffer.AbstractByteBuf.readSlice(AbstractByteBuf.java:856)
[info]   at io.netty.handler.codec.ReplayingDecoderByteBuf.readSlice(ReplayingDecoderByteBuf.java:583)
[info]   at com.wavesplatform.network.Handshake$.decode(Handshake.scala:54)
[info]   at com.wavesplatform.network.HandshakeDecoder.decode(HandshakeHandler.scala:22)
[info]   at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
[info]   at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
[info]   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[info]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[info]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[info]   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[info]   at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[info]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[info]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[info]   at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[info]   at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:325)
[info]   at com.wavesplatform.network.HandshakeDecoderSpec.$anonfun$new$3(HandshakeDecoderSpec.scala:95)
[info]   at org.scalatest.prop.GeneratorDrivenPropertyChecks.liftedTree9$1(GeneratorDrivenPropertyChecks.scala:931)
[info]   at org.scalatest.prop.GeneratorDrivenPropertyChecks.$anonfun$forAll$7(GeneratorDrivenPropertyChecks.scala:930)
[info]   at org.scalacheck.Prop$.$anonfun$forAllShrink$2(Prop.scala:712)
[info]   at org.scalacheck.Prop$.secure(Prop.scala:456)
[info]   at org.scalacheck.Prop$.result$1(Prop.scala:712)
[info]   at org.scalacheck.Prop$.$anonfun$forAllShrink$1(Prop.scala:749)
[info]   at org.scalacheck.Prop$.$anonfun$apply$1(Prop.scala:292)
[info]   at org.scalacheck.PropFromFun.apply(Prop.scala:22)
[info]   at org.scalacheck.Test$.workerFun$1(Test.scala:294)
[info]   at org.scalacheck.Test$.$anonfun$check$1(Test.scala:323)
[info]   at org.scalacheck.Test$.$anonfun$check$1$adapted(Test.scala:323)
[info]   at org.scalacheck.Platform$.runWorkers(Platform.scala:40)
[info]   at org.scalacheck.Test$.check(Test.scala:323)
[info]   at org.scalatest.enablers.UnitCheckerAsserting$CheckerAssertingImpl.check(CheckerAsserting.scala:89)
[info]   at org.scalatest.prop.GeneratorDrivenPropertyChecks.forAll(GeneratorDrivenPropertyChecks.scala:944)
[info]   at org.scalatest.prop.GeneratorDrivenPropertyChecks.forAll$(GeneratorDrivenPropertyChecks.scala:920)
[info]   at com.wavesplatform.network.HandshakeDecoderSpec.forAll(HandshakeDecoderSpec.scala:16)
[info]   at com.wavesplatform.network.HandshakeDecoderSpec.$anonfun$new$2(HandshakeDecoderSpec.scala:88)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.FreeSpecLike$$anon$1.apply(FreeSpecLike.scala:407)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[info]   at com.wavesplatform.network.HandshakeDecoderSpec.org$scalamock$scalatest$AbstractMockFactory$$super$withFixture(HandshakeDecoderSpec.scala:16)
[info]   at org.scalamock.scalatest.AbstractMockFactory.$anonfun$withFixture$1(AbstractMockFactory.scala:35)
[info]   at org.scalamock.MockFactoryBase.withExpectations(MockFactoryBase.scala:55)
[info]   at org.scalamock.MockFactoryBase.withExpectations$(MockFactoryBase.scala:47)
[info]   at com.wavesplatform.network.HandshakeDecoderSpec.withExpectations(HandshakeDecoderSpec.scala:16)
[info]   at org.scalamock.scalatest.AbstractMockFactory.withFixture(AbstractMockFactory.scala:34)
[info]   at org.scalamock.scalatest.AbstractMockFactory.withFixture$(AbstractMockFactory.scala:31)
[info]   at com.wavesplatform.network.HandshakeDecoderSpec.withFixture(HandshakeDecoderSpec.scala:16)
[info]   at org.scalatest.FreeSpecLike.invokeWithFixture$1(FreeSpecLike.scala:405)
[info]   at org.scalatest.FreeSpecLike.$anonfun$runTest$1(FreeSpecLike.scala:417)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.FreeSpecLike.runTest(FreeSpecLike.scala:417)
[info]   at org.scalatest.FreeSpecLike.runTest$(FreeSpecLike.scala:399)
[info]   at org.scalatest.FreeSpec.runTest(FreeSpec.scala:1739)
[info]   at org.scalatest.FreeSpecLike.$anonfun$runTests$1(FreeSpecLike.scala:476)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
[info]   at scala.collection.immutable.List.foreach(List.scala:389)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[info]   at org.scalatest.FreeSpecLike.runTests(FreeSpecLike.scala:476)
[info]   at org.scalatest.FreeSpecLike.runTests$(FreeSpecLike.scala:475)
[info]   at org.scalatest.FreeSpec.runTests(FreeSpec.scala:1739)
[info]   at org.scalatest.Suite.run(Suite.scala:1147)
[info]   at org.scalatest.Suite.run$(Suite.scala:1129)
[info]   at org.scalatest.FreeSpec.org$scalatest$FreeSpecLike$$super$run(FreeSpec.scala:1739)
[info]   at org.scalatest.FreeSpecLike.$anonfun$run$1(FreeSpecLike.scala:520)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[info]   at org.scalatest.FreeSpecLike.run(FreeSpecLike.scala:520)
[info]   at org.scalatest.FreeSpecLike.run$(FreeSpecLike.scala:519)
[info]   at org.scalatest.FreeSpec.run(FreeSpec.scala:1739)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:507)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:106)
[info]   at sbt.TestRunner.run(TestFramework.scala:117)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:262)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:233)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:262)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:262)
[info]   at sbt.TestFunction.apply(TestFramework.scala:271)
[info]   at sbt.Tests$.processRunnable$1(Tests.scala:307)
[info]   at sbt.Tests$.$anonfun$makeSerial$1(Tests.scala:313)
[info]   at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
[info]   at sbt.std.Transform$$anon$4.work(System.scala:66)
[info]   at sbt.Execute.$anonfun$submit$2(Execute.scala:262)
[info]   at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[info]   at sbt.Execute.work(Execute.scala:271)
[info]   at sbt.Execute.$anonfun$submit$1(Execute.scala:262)
[info]   at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:36)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:748)
```
